[package]
name = "zip-brute-force"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.1"
sha-1 = "0.10"
sha2 = "0.10.2"
zip = "0.6.2"
indicatif = "0.17.0"
colored = "2.0"
tiger = "0.2"
